In [1]:
import numpy as np
data=np.load('Thousand_bp_data.npz')
A=data['arr_0']
B=data['arr_1']

In [2]:
A

array([[0.25, 0.25, 0.5 , ..., 1.  , 1.  , 0.25],
       [0.5 , 0.25, 1.  , ..., 0.5 , 0.25, 0.5 ],
       [0.25, 0.75, 0.25, ..., 0.5 , 0.25, 0.25],
       ...,
       [1.  , 0.25, 0.5 , ..., 0.25, 0.75, 0.75],
       [0.5 , 0.75, 0.5 , ..., 0.25, 0.25, 0.75],
       [0.75, 0.75, 0.5 , ..., 1.  , 0.75, 0.5 ]])

In [3]:
B

array([[0.25, 1.  , 1.  , ..., 0.25, 1.  , 1.  ],
       [1.  , 1.  , 1.  , ..., 1.  , 0.25, 1.  ],
       [1.  , 1.  , 0.75, ..., 0.25, 0.25, 1.  ],
       ...,
       [0.5 , 0.75, 1.  , ..., 0.5 , 1.  , 1.  ],
       [0.75, 1.  , 1.  , ..., 1.  , 1.  , 1.  ],
       [1.  , 1.  , 0.75, ..., 1.  , 0.25, 1.  ]])

In [4]:
np.shape(B)

(356863, 1001)

In [5]:
np.shape(A)

(356863, 1000)

In [6]:
non_path_labelled = np.hstack((A, np.atleast_2d(np.zeros(len(A))).T))

In [7]:
non_path_labelled

array([[0.25, 0.25, 0.5 , ..., 1.  , 0.25, 0.  ],
       [0.5 , 0.25, 1.  , ..., 0.25, 0.5 , 0.  ],
       [0.25, 0.75, 0.25, ..., 0.25, 0.25, 0.  ],
       ...,
       [1.  , 0.25, 0.5 , ..., 0.75, 0.75, 0.  ],
       [0.5 , 0.75, 0.5 , ..., 0.25, 0.75, 0.  ],
       [0.75, 0.75, 0.5 , ..., 0.75, 0.5 , 0.  ]])

In [8]:
path_labelled=B;
path_labelled

array([[0.25, 1.  , 1.  , ..., 0.25, 1.  , 1.  ],
       [1.  , 1.  , 1.  , ..., 1.  , 0.25, 1.  ],
       [1.  , 1.  , 0.75, ..., 0.25, 0.25, 1.  ],
       ...,
       [0.5 , 0.75, 1.  , ..., 0.5 , 1.  , 1.  ],
       [0.75, 1.  , 1.  , ..., 1.  , 1.  , 1.  ],
       [1.  , 1.  , 0.75, ..., 1.  , 0.25, 1.  ]])

In [9]:
data=np.concatenate((non_path_labelled,path_labelled),axis=0)

In [10]:
data

array([[0.25, 0.25, 0.5 , ..., 1.  , 0.25, 0.  ],
       [0.5 , 0.25, 1.  , ..., 0.25, 0.5 , 0.  ],
       [0.25, 0.75, 0.25, ..., 0.25, 0.25, 0.  ],
       ...,
       [0.5 , 0.75, 1.  , ..., 0.5 , 1.  , 1.  ],
       [0.75, 1.  , 1.  , ..., 1.  , 1.  , 1.  ],
       [1.  , 1.  , 0.75, ..., 1.  , 0.25, 1.  ]])

In [11]:
np.shape(data)

(713726, 1001)

In [12]:
y_raw=data[:,-1]
y_raw

array([0., 0., 0., ..., 1., 1., 1.])

In [13]:
X_raw=np.delete(data,-1,axis=1)
X_raw

array([[0.25, 0.25, 0.5 , ..., 1.  , 1.  , 0.25],
       [0.5 , 0.25, 1.  , ..., 0.5 , 0.25, 0.5 ],
       [0.25, 0.75, 0.25, ..., 0.5 , 0.25, 0.25],
       ...,
       [0.5 , 0.75, 1.  , ..., 1.  , 0.5 , 1.  ],
       [0.75, 1.  , 1.  , ..., 0.5 , 1.  , 1.  ],
       [1.  , 1.  , 0.75, ..., 1.  , 1.  , 0.25]])

In [14]:
y_raw.reshape(len(y_raw),1)

array([[0.],
       [0.],
       [0.],
       ...,
       [1.],
       [1.],
       [1.]])

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X_raw, y_raw.reshape(len(y_raw),1), test_size=0.5, random_state=101)

In [16]:
np.savez('Thousand_bp_trial2',X_train,y_train,X_test,y_test,'Xtrain','ytrain','Xtest','ytest')